# Use Node for development
FROM node:25

WORKDIR /app

COPY package*.json ./

RUN rm -rf node_modules package-lock.json && \
    npm install --force

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
