// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LoginGoogleResponse, AuthGoogleCallbackResponse, LoginAccessTokenData, LoginAccessTokenResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, PrivateCreateUserData, PrivateCreateUserResponse, ShiftRequestsGetLeaveCodesResponse, ShiftRequestsGetAllShiftCodesResponse, ShiftRequestsGetWorkingShiftCodesResponse, ShiftRequestsGetShiftCodesByWardData, ShiftRequestsGetShiftCodesByWardResponse, ShiftRequestsGetRosterPeriodsResponse, ShiftRequestsGetRosterPeriodData, ShiftRequestsGetRosterPeriodResponse, ShiftRequestsGetUserShiftRequestsResponse, ShiftRequestsCreateShiftRequestData, ShiftRequestsCreateShiftRequestResponse, ShiftRequestsGetShiftRequestsByWardData, ShiftRequestsGetShiftRequestsByWardResponse, ShiftRequestsUpdateShiftRequestData, ShiftRequestsUpdateShiftRequestResponse, ShiftRequestsDeleteShiftRequestData, ShiftRequestsDeleteShiftRequestResponse, ShiftRequestsGetWardNursesData, ShiftRequestsGetWardNursesResponse, ShiftRequestsReviewShiftRequestData, ShiftRequestsReviewShiftRequestResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse, WardsGetWardsResponse, Ward } from './types.gen';

export class DefaultService {
    /**
     * Login Google
     * Initiate Google OAuth login
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static loginGoogle(): CancelablePromise<LoginGoogleResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/login/google'
        });
    }
    
    /**
     * Auth Google Callback
     * Handle Google OAuth callback
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static authGoogleCallback(): CancelablePromise<AuthGoogleCallbackResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/auth/google/callback'
        });
    }
    
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns string Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginAccessTokenData): CancelablePromise<LoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ShiftRequestsService {
    /**
     * Get Leave Codes
     * Get all shift codes where isworking is false.
     * @returns ShiftCodePublic Successful Response
     * @throws ApiError
     */
    public static getLeaveCodes(): CancelablePromise<ShiftRequestsGetLeaveCodesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/shift-requests/leave-codes'
        });
    }
    
    /**
     * Get All Shift Codes
     * Get all shift codes.
     * @returns ShiftCodePublic Successful Response
     * @throws ApiError
     */
    public static getAllShiftCodes(): CancelablePromise<ShiftRequestsGetAllShiftCodesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/shift-requests/shift-codes'
        });
    }
    
    /**
     * Get Working Shift Codes
     * Get all shift codes where isworking is true.
     * @returns ShiftCodePublic Successful Response
     * @throws ApiError
     */
    public static getWorkingShiftCodes(): CancelablePromise<ShiftRequestsGetWorkingShiftCodesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/shift-requests/shift-codes/working'
        });
    }
    
    /**
     * Get Shift Codes By Ward
     * Get applicable shift codes for a ward.
     * Falls back to all working shift codes if no mappings are configured for that ward.
     * @param data The data for the request.
     * @param data.wardId
     * @returns ShiftCodePublic Successful Response
     * @throws ApiError
     */
    public static getShiftCodesByWard(data: ShiftRequestsGetShiftCodesByWardData): CancelablePromise<ShiftRequestsGetShiftCodesByWardResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/shift-requests/shift-codes/ward/{ward_id}',
            path: {
                ward_id: data.wardId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Roster Periods
     * Get all roster periods.
     * @returns RosterPeriodPublic Successful Response
     * @throws ApiError
     */
    public static getRosterPeriods(): CancelablePromise<ShiftRequestsGetRosterPeriodsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/shift-requests/periods'
        });
    }
    
    /**
     * Get Roster Period
     * Get the roster period that contains the given date.
     * @param data The data for the request.
     * @param data.targetDate Date to find the roster period for
     * @returns RosterPeriodPublic Successful Response
     * @throws ApiError
     */
    public static getRosterPeriod(data: ShiftRequestsGetRosterPeriodData): CancelablePromise<ShiftRequestsGetRosterPeriodResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/shift-requests/period',
            query: {
                target_date: data.targetDate
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get User Shift Requests
     * Get all shift requests for the current user.
     * @returns ShiftRequestPublic Successful Response
     * @throws ApiError
     */
    public static getUserShiftRequests(): CancelablePromise<ShiftRequestsGetUserShiftRequestsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/shift-requests/'
        });
    }
    
    /**
     * Create Shift Request
     * Create a shift request for the logged-in nurse.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ShiftRequestPublic Successful Response
     * @throws ApiError
     */
    public static createShiftRequest(data: ShiftRequestsCreateShiftRequestData): CancelablePromise<ShiftRequestsCreateShiftRequestResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/shift-requests/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Shift Requests By Ward
     * Get all shift requests for nurses in a specific ward.
     * @param data The data for the request.
     * @param data.wardId
     * @param data.periodId
     * @returns ShiftRequestPublic Successful Response
     * @throws ApiError
     */
    public static getShiftRequestsByWard(data: ShiftRequestsGetShiftRequestsByWardData): CancelablePromise<ShiftRequestsGetShiftRequestsByWardResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/shift-requests/ward/{ward_id}',
            path: {
                ward_id: data.wardId
            },
            query: {
                period_id: data.periodId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Shift Request
     * Update a shift request (shift type and/or date). Only the owning nurse can update.
     * @param data The data for the request.
     * @param data.requestId
     * @param data.requestBody
     * @returns ShiftRequestPublic Successful Response
     * @throws ApiError
     */
    public static updateShiftRequest(data: ShiftRequestsUpdateShiftRequestData): CancelablePromise<ShiftRequestsUpdateShiftRequestResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/shift-requests/{request_id}',
            path: {
                request_id: data.requestId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Shift Request
     * Delete a shift request. Only the owning nurse can delete.
     * @param data The data for the request.
     * @param data.requestId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static deleteShiftRequest(data: ShiftRequestsDeleteShiftRequestData): CancelablePromise<ShiftRequestsDeleteShiftRequestResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/shift-requests/{request_id}',
            path: {
                request_id: data.requestId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Review Shift Request
     * Approve or reject a shift request (nurse manager action).
     * @param data The data for the request.
     * @param data.requestId
     * @param data.requestBody
     * @returns ShiftRequestPublic Successful Response
     * @throws ApiError
     */
    public static reviewShiftRequest(data: ShiftRequestsReviewShiftRequestData): CancelablePromise<ShiftRequestsReviewShiftRequestResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/shift-requests/{request_id}/review',
            path: {
                request_id: data.requestId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Get Ward Nurses
     * Get all nurses for a specific ward.
     * @param data The data for the request.
     * @param data.wardId
     * @returns NursePublic Successful Response
     * @throws ApiError
     */
    public static getWardNurses(data: ShiftRequestsGetWardNursesData): CancelablePromise<ShiftRequestsGetWardNursesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/shift-requests/ward/{ward_id}/nurses',
            path: {
                ward_id: data.wardId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}

export class WardsService {
    /**
     * Get Wards
     * @returns Ward Successful Response
     * @throws ApiError
     */
    public static getWards(): CancelablePromise<WardsGetWardsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/wards/'
        });
    }

    /**
     * Get Ward
     * Get a single ward by ID.
     * @param data The data for the request.
     * @param data.wardId
     * @returns Ward Successful Response
     * @throws ApiError
     */
    public static getWard(data: { wardId: number }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/wards/{ward_id}',
            path: {
                ward_id: data.wardId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Create Ward
     * Create a new ward (admin only).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Ward Successful Response
     * @throws ApiError
     */
    public static createWard(data: { requestBody: Ward }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/wards/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Update Ward
     * Update ward details (admin only).
     * @param data The data for the request.
     * @param data.wardId
     * @param data.requestBody
     * @returns Ward Successful Response
     * @throws ApiError
     */
    public static updateWard(data: { wardId: number; requestBody: Partial<Ward> }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/wards/{ward_id}',
            path: {
                ward_id: data.wardId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Delete Ward
     * Delete a ward (admin only).
     * @param data The data for the request.
     * @param data.wardId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteWard(data: { wardId: number }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/wards/{ward_id}',
            path: {
                ward_id: data.wardId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class HomeService {
    /**
     * Get Upcoming Shift
     * Get the next upcoming shift for the authenticated user.
     * @returns UpcomingShiftResponse Successful Response
     * @throws ApiError
     */
    public static getUpcomingShift(): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/home/upcoming-shift',
            errors: {
                404: 'Not Found',
                422: 'Validation Error'
            }
        });
    }

    /**
     * Get My Shifts
     * Get confirmed roster shifts for the authenticated nurse, optionally filtered by date range.
     * @returns RosterShiftPublic[] Successful Response
     * @throws ApiError
     */
    public static getMyShifts(data?: { startDate?: string; endDate?: string }): CancelablePromise<Array<{
        shiftdate: string;
        shiftcode: string;
        starttime: string | null;
        endtime: string | null;
        description: string | null;
    }>> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/home/my-shifts',
            query: {
                start_date: data?.startDate,
                end_date: data?.endDate,
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}