// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NursePublic = {
    nurseid: number;
    name: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RosterPeriodPublic = {
    periodid: number;
    name: string;
    startdate: string;
    enddate: string;
    status: string;
};

export type ShiftCodePublic = {
    shiftcode: string;
    description: string;
    isworking: boolean;
    shiftdurationhours?: number | null;
    defaultstart?: string | null;
    defaultend?: string | null;
};

export type ShiftRequestCreate = {
    periodid: number;
    preferreddate: string;
    preferredshifttype: string;
    reason?: (string | null);
    priority?: number;
};

export type ShiftRequestPublic = {
    requestid: number;
    nurseid: number;
    periodid: number;
    preferreddate: string;
    preferredshifttype: string;
    requestnumber: number;
    reason: (string | null);
    priority: number;
    status: string;
};

export type ShiftRequestUpdate = {
    preferredshifttype?: (string | null);
    preferreddate?: (string | null);
};

export type ShiftRequestReview = {
    status: string;
    rejectionreason?: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    nurseid?: (number | null);
    managerid?: (number | null);
    wardid?: (number | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type Ward = {
    wardid?: (number | null);
    wardname: string;
    wardtype?: (string | null);
    location?: (string | null);
    isactive?: boolean;
    am_total?: (number | null);
    am_rn?: (number | null);
    am_en_na_min?: (number | null);
    am_en_na_max?: (number | null);
    am_hca_min?: (number | null);
    am_hca_max?: (number | null);
    pm_total?: (number | null);
    pm_rn?: (number | null);
    pm_en_na_min?: (number | null);
    pm_en_na_max?: (number | null);
    pm_hca_min?: (number | null);
    pm_hca_max?: (number | null);
    nd_total?: (number | null);
    nd_rn?: (number | null);
    nd_en_na_min?: (number | null);
    nd_en_na_max?: (number | null);
    nd_hca_min?: (number | null);
    nd_hca_max?: (number | null);
};

export type LoginGoogleResponse = (unknown);

export type AuthGoogleCallbackResponse = (unknown);

export type LoginAccessTokenData = {
    formData: Body_login_access_token;
};

export type LoginAccessTokenResponse = ({
    [key: string]: (string);
});

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ShiftRequestsGetLeaveCodesResponse = (Array<ShiftCodePublic>);

export type ShiftRequestsGetAllShiftCodesResponse = (Array<ShiftCodePublic>);

export type ShiftRequestsGetWorkingShiftCodesResponse = (Array<ShiftCodePublic>);

export type ShiftRequestsGetShiftCodesByWardData = {
    wardId: number;
};

export type ShiftRequestsGetShiftCodesByWardResponse = (Array<ShiftCodePublic>);

export type ShiftRequestsGetRosterPeriodsResponse = (Array<RosterPeriodPublic>);

export type ShiftRequestsGetRosterPeriodData = {
    /**
     * Date to find the roster period for
     */
    targetDate: string;
};

export type ShiftRequestsGetRosterPeriodResponse = (RosterPeriodPublic);

export type ShiftRequestsGetUserShiftRequestsResponse = (Array<ShiftRequestPublic>);

export type ShiftRequestsCreateShiftRequestData = {
    requestBody: ShiftRequestCreate;
};

export type ShiftRequestsCreateShiftRequestResponse = (ShiftRequestPublic);

export type ShiftRequestsGetShiftRequestsByWardData = {
    periodId?: (number | null);
    wardId: number;
};

export type ShiftRequestsGetShiftRequestsByWardResponse = (Array<ShiftRequestPublic>);

export type ShiftRequestsUpdateShiftRequestData = {
    requestBody: ShiftRequestUpdate;
    requestId: number;
};

export type ShiftRequestsUpdateShiftRequestResponse = (ShiftRequestPublic);

export type ShiftRequestsDeleteShiftRequestData = {
    requestId: number;
};

export type ShiftRequestsDeleteShiftRequestResponse = (void);

export type ShiftRequestsReviewShiftRequestData = {
    requestBody: ShiftRequestReview;
    requestId: number;
};

export type ShiftRequestsReviewShiftRequestResponse = (ShiftRequestPublic);

export type ShiftRequestsGetWardNursesData = {
    wardId: number;
};

export type ShiftRequestsGetWardNursesResponse = (Array<NursePublic>);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WardsGetWardsResponse = (Array<Ward>);
