"""add password reset token columns to rbacuser

Revision ID: a3f9d2e1b8c7
Revises: g2h3i4j5k6l7
Create Date: 2025-01-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'a3f9d2e1b8c7'
down_revision: Union[str, None] = 'g2h3i4j5k6l7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()

    if 'rbacuser' not in tables:
        # Table doesn't exist yet (created later by SQLModel.metadata.create_all)
        # The columns will be present when the table is created from the model
        return

    columns = [col['name'] for col in inspector.get_columns('rbacuser')]

    if 'password_reset_token' not in columns:
        op.add_column(
            'rbacuser',
            sa.Column('password_reset_token', sa.String(length=128), nullable=True)
        )

    if 'password_reset_token_expires_at' not in columns:
        op.add_column(
            'rbacuser',
            sa.Column(
                'password_reset_token_expires_at',
                sa.DateTime(timezone=True),
                nullable=True
            )
        )

    indexes = [idx['name'] for idx in inspector.get_indexes('rbacuser')]
    if 'ix_rbacuser_password_reset_token' not in indexes:
        op.create_index(
            'ix_rbacuser_password_reset_token',
            'rbacuser',
            ['password_reset_token'],
            unique=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()

    if 'rbacuser' not in tables:
        return

    indexes = [idx['name'] for idx in inspector.get_indexes('rbacuser')]
    if 'ix_rbacuser_password_reset_token' in indexes:
        op.drop_index('ix_rbacuser_password_reset_token', table_name='rbacuser')

    columns = [col['name'] for col in inspector.get_columns('rbacuser')]
    if 'password_reset_token_expires_at' in columns:
        op.drop_column('rbacuser', 'password_reset_token_expires_at')
    if 'password_reset_token' in columns:
        op.drop_column('rbacuser', 'password_reset_token')
    # ### end Alembic commands ###