/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WardStaffRouteImport } from './routes/ward-staff'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as NurseManagerRouteImport } from './routes/nurse-manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WardStaffIndexRouteImport } from './routes/ward-staff/index'
import { Route as NurseManagerIndexRouteImport } from './routes/nurse-manager/index'
import { Route as WardStaffStaffrosterscheduleRouteImport } from './routes/ward-staff/staffrosterschedule'
import { Route as WardStaffShiftRequestRouteImport } from './routes/ward-staff/shift-request'
import { Route as WardStaffSettingsRouteImport } from './routes/ward-staff/settings'
import { Route as WardStaffRequestApplicationRouteImport } from './routes/ward-staff/request-application'
import { Route as WardStaffLeaveandshiftrequestRouteImport } from './routes/ward-staff/leaveandshiftrequest'
import { Route as WardStaffLeaveRequestRouteImport } from './routes/ward-staff/leave-request'
import { Route as WardStaffHomeRouteImport } from './routes/ward-staff/home'
import { Route as NurseManagerWardStaffDirectoryRouteImport } from './routes/nurse-manager/ward-staff-directory'
import { Route as NurseManagerSettingsRouteImport } from './routes/nurse-manager/settings'
import { Route as NurseManagerRosterPlanningRouteImport } from './routes/nurse-manager/roster-planning'
import { Route as NurseManagerRequestOverviewRouteImport } from './routes/nurse-manager/request-overview'
import { Route as NurseManagerRequestApplicationRouteImport } from './routes/nurse-manager/request-application'
import { Route as NurseManagerHomeRouteImport } from './routes/nurse-manager/home'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const WardStaffRoute = WardStaffRouteImport.update({
  id: '/ward-staff',
  path: '/ward-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseManagerRoute = NurseManagerRouteImport.update({
  id: '/nurse-manager',
  path: '/nurse-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WardStaffIndexRoute = WardStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WardStaffRoute,
} as any)
const NurseManagerIndexRoute = NurseManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NurseManagerRoute,
} as any)
const WardStaffStaffrosterscheduleRoute =
  WardStaffStaffrosterscheduleRouteImport.update({
    id: '/staffrosterschedule',
    path: '/staffrosterschedule',
    getParentRoute: () => WardStaffRoute,
  } as any)
const WardStaffShiftRequestRoute = WardStaffShiftRequestRouteImport.update({
  id: '/shift-request',
  path: '/shift-request',
  getParentRoute: () => WardStaffRoute,
} as any)
const WardStaffSettingsRoute = WardStaffSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WardStaffRoute,
} as any)
const WardStaffRequestApplicationRoute =
  WardStaffRequestApplicationRouteImport.update({
    id: '/request-application',
    path: '/request-application',
    getParentRoute: () => WardStaffRoute,
  } as any)
const WardStaffLeaveandshiftrequestRoute =
  WardStaffLeaveandshiftrequestRouteImport.update({
    id: '/leaveandshiftrequest',
    path: '/leaveandshiftrequest',
    getParentRoute: () => WardStaffRoute,
  } as any)
const WardStaffLeaveRequestRoute = WardStaffLeaveRequestRouteImport.update({
  id: '/leave-request',
  path: '/leave-request',
  getParentRoute: () => WardStaffRoute,
} as any)
const WardStaffHomeRoute = WardStaffHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => WardStaffRoute,
} as any)
const NurseManagerWardStaffDirectoryRoute =
  NurseManagerWardStaffDirectoryRouteImport.update({
    id: '/ward-staff-directory',
    path: '/ward-staff-directory',
    getParentRoute: () => NurseManagerRoute,
  } as any)
const NurseManagerSettingsRoute = NurseManagerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => NurseManagerRoute,
} as any)
const NurseManagerRosterPlanningRoute =
  NurseManagerRosterPlanningRouteImport.update({
    id: '/roster-planning',
    path: '/roster-planning',
    getParentRoute: () => NurseManagerRoute,
  } as any)
const NurseManagerRequestOverviewRoute =
  NurseManagerRequestOverviewRouteImport.update({
    id: '/request-overview',
    path: '/request-overview',
    getParentRoute: () => NurseManagerRoute,
  } as any)
const NurseManagerRequestApplicationRoute =
  NurseManagerRequestApplicationRouteImport.update({
    id: '/request-application',
    path: '/request-application',
    getParentRoute: () => NurseManagerRoute,
  } as any)
const NurseManagerHomeRoute = NurseManagerHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => NurseManagerRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/nurse-manager': typeof NurseManagerRouteWithChildren
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/ward-staff': typeof WardStaffRouteWithChildren
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/nurse-manager/home': typeof NurseManagerHomeRoute
  '/nurse-manager/request-application': typeof NurseManagerRequestApplicationRoute
  '/nurse-manager/request-overview': typeof NurseManagerRequestOverviewRoute
  '/nurse-manager/roster-planning': typeof NurseManagerRosterPlanningRoute
  '/nurse-manager/settings': typeof NurseManagerSettingsRoute
  '/nurse-manager/ward-staff-directory': typeof NurseManagerWardStaffDirectoryRoute
  '/ward-staff/home': typeof WardStaffHomeRoute
  '/ward-staff/leave-request': typeof WardStaffLeaveRequestRoute
  '/ward-staff/leaveandshiftrequest': typeof WardStaffLeaveandshiftrequestRoute
  '/ward-staff/request-application': typeof WardStaffRequestApplicationRoute
  '/ward-staff/settings': typeof WardStaffSettingsRoute
  '/ward-staff/shift-request': typeof WardStaffShiftRequestRoute
  '/ward-staff/staffrosterschedule': typeof WardStaffStaffrosterscheduleRoute
  '/nurse-manager/': typeof NurseManagerIndexRoute
  '/ward-staff/': typeof WardStaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/nurse-manager/home': typeof NurseManagerHomeRoute
  '/nurse-manager/request-application': typeof NurseManagerRequestApplicationRoute
  '/nurse-manager/request-overview': typeof NurseManagerRequestOverviewRoute
  '/nurse-manager/roster-planning': typeof NurseManagerRosterPlanningRoute
  '/nurse-manager/settings': typeof NurseManagerSettingsRoute
  '/nurse-manager/ward-staff-directory': typeof NurseManagerWardStaffDirectoryRoute
  '/ward-staff/home': typeof WardStaffHomeRoute
  '/ward-staff/leave-request': typeof WardStaffLeaveRequestRoute
  '/ward-staff/leaveandshiftrequest': typeof WardStaffLeaveandshiftrequestRoute
  '/ward-staff/request-application': typeof WardStaffRequestApplicationRoute
  '/ward-staff/settings': typeof WardStaffSettingsRoute
  '/ward-staff/shift-request': typeof WardStaffShiftRequestRoute
  '/ward-staff/staffrosterschedule': typeof WardStaffStaffrosterscheduleRoute
  '/nurse-manager': typeof NurseManagerIndexRoute
  '/ward-staff': typeof WardStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/nurse-manager': typeof NurseManagerRouteWithChildren
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/ward-staff': typeof WardStaffRouteWithChildren
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/nurse-manager/home': typeof NurseManagerHomeRoute
  '/nurse-manager/request-application': typeof NurseManagerRequestApplicationRoute
  '/nurse-manager/request-overview': typeof NurseManagerRequestOverviewRoute
  '/nurse-manager/roster-planning': typeof NurseManagerRosterPlanningRoute
  '/nurse-manager/settings': typeof NurseManagerSettingsRoute
  '/nurse-manager/ward-staff-directory': typeof NurseManagerWardStaffDirectoryRoute
  '/ward-staff/home': typeof WardStaffHomeRoute
  '/ward-staff/leave-request': typeof WardStaffLeaveRequestRoute
  '/ward-staff/leaveandshiftrequest': typeof WardStaffLeaveandshiftrequestRoute
  '/ward-staff/request-application': typeof WardStaffRequestApplicationRoute
  '/ward-staff/settings': typeof WardStaffSettingsRoute
  '/ward-staff/shift-request': typeof WardStaffShiftRequestRoute
  '/ward-staff/staffrosterschedule': typeof WardStaffStaffrosterscheduleRoute
  '/nurse-manager/': typeof NurseManagerIndexRoute
  '/ward-staff/': typeof WardStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/nurse-manager'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/ward-staff'
    | '/admin'
    | '/items'
    | '/auth/callback'
    | '/nurse-manager/home'
    | '/nurse-manager/request-application'
    | '/nurse-manager/request-overview'
    | '/nurse-manager/roster-planning'
    | '/nurse-manager/settings'
    | '/nurse-manager/ward-staff-directory'
    | '/ward-staff/home'
    | '/ward-staff/leave-request'
    | '/ward-staff/leaveandshiftrequest'
    | '/ward-staff/request-application'
    | '/ward-staff/settings'
    | '/ward-staff/shift-request'
    | '/ward-staff/staffrosterschedule'
    | '/nurse-manager/'
    | '/ward-staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/auth/callback'
    | '/nurse-manager/home'
    | '/nurse-manager/request-application'
    | '/nurse-manager/request-overview'
    | '/nurse-manager/roster-planning'
    | '/nurse-manager/settings'
    | '/nurse-manager/ward-staff-directory'
    | '/ward-staff/home'
    | '/ward-staff/leave-request'
    | '/ward-staff/leaveandshiftrequest'
    | '/ward-staff/request-application'
    | '/ward-staff/settings'
    | '/ward-staff/shift-request'
    | '/ward-staff/staffrosterschedule'
    | '/nurse-manager'
    | '/ward-staff'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/nurse-manager'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/ward-staff'
    | '/_layout/admin'
    | '/_layout/items'
    | '/auth/callback'
    | '/nurse-manager/home'
    | '/nurse-manager/request-application'
    | '/nurse-manager/request-overview'
    | '/nurse-manager/roster-planning'
    | '/nurse-manager/settings'
    | '/nurse-manager/ward-staff-directory'
    | '/ward-staff/home'
    | '/ward-staff/leave-request'
    | '/ward-staff/leaveandshiftrequest'
    | '/ward-staff/request-application'
    | '/ward-staff/settings'
    | '/ward-staff/shift-request'
    | '/ward-staff/staffrosterschedule'
    | '/nurse-manager/'
    | '/ward-staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  NurseManagerRoute: typeof NurseManagerRouteWithChildren
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  WardStaffRoute: typeof WardStaffRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ward-staff': {
      id: '/ward-staff'
      path: '/ward-staff'
      fullPath: '/ward-staff'
      preLoaderRoute: typeof WardStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse-manager': {
      id: '/nurse-manager'
      path: '/nurse-manager'
      fullPath: '/nurse-manager'
      preLoaderRoute: typeof NurseManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ward-staff/': {
      id: '/ward-staff/'
      path: '/'
      fullPath: '/ward-staff/'
      preLoaderRoute: typeof WardStaffIndexRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/nurse-manager/': {
      id: '/nurse-manager/'
      path: '/'
      fullPath: '/nurse-manager/'
      preLoaderRoute: typeof NurseManagerIndexRouteImport
      parentRoute: typeof NurseManagerRoute
    }
    '/ward-staff/staffrosterschedule': {
      id: '/ward-staff/staffrosterschedule'
      path: '/staffrosterschedule'
      fullPath: '/ward-staff/staffrosterschedule'
      preLoaderRoute: typeof WardStaffStaffrosterscheduleRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/ward-staff/shift-request': {
      id: '/ward-staff/shift-request'
      path: '/shift-request'
      fullPath: '/ward-staff/shift-request'
      preLoaderRoute: typeof WardStaffShiftRequestRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/ward-staff/settings': {
      id: '/ward-staff/settings'
      path: '/settings'
      fullPath: '/ward-staff/settings'
      preLoaderRoute: typeof WardStaffSettingsRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/ward-staff/request-application': {
      id: '/ward-staff/request-application'
      path: '/request-application'
      fullPath: '/ward-staff/request-application'
      preLoaderRoute: typeof WardStaffRequestApplicationRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/ward-staff/leaveandshiftrequest': {
      id: '/ward-staff/leaveandshiftrequest'
      path: '/leaveandshiftrequest'
      fullPath: '/ward-staff/leaveandshiftrequest'
      preLoaderRoute: typeof WardStaffLeaveandshiftrequestRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/ward-staff/leave-request': {
      id: '/ward-staff/leave-request'
      path: '/leave-request'
      fullPath: '/ward-staff/leave-request'
      preLoaderRoute: typeof WardStaffLeaveRequestRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/ward-staff/home': {
      id: '/ward-staff/home'
      path: '/home'
      fullPath: '/ward-staff/home'
      preLoaderRoute: typeof WardStaffHomeRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/nurse-manager/ward-staff-directory': {
      id: '/nurse-manager/ward-staff-directory'
      path: '/ward-staff-directory'
      fullPath: '/nurse-manager/ward-staff-directory'
      preLoaderRoute: typeof NurseManagerWardStaffDirectoryRouteImport
      parentRoute: typeof NurseManagerRoute
    }
    '/nurse-manager/settings': {
      id: '/nurse-manager/settings'
      path: '/settings'
      fullPath: '/nurse-manager/settings'
      preLoaderRoute: typeof NurseManagerSettingsRouteImport
      parentRoute: typeof NurseManagerRoute
    }
    '/nurse-manager/roster-planning': {
      id: '/nurse-manager/roster-planning'
      path: '/roster-planning'
      fullPath: '/nurse-manager/roster-planning'
      preLoaderRoute: typeof NurseManagerRosterPlanningRouteImport
      parentRoute: typeof NurseManagerRoute
    }
    '/nurse-manager/request-overview': {
      id: '/nurse-manager/request-overview'
      path: '/request-overview'
      fullPath: '/nurse-manager/request-overview'
      preLoaderRoute: typeof NurseManagerRequestOverviewRouteImport
      parentRoute: typeof NurseManagerRoute
    }
    '/nurse-manager/request-application': {
      id: '/nurse-manager/request-application'
      path: '/request-application'
      fullPath: '/nurse-manager/request-application'
      preLoaderRoute: typeof NurseManagerRequestApplicationRouteImport
      parentRoute: typeof NurseManagerRoute
    }
    '/nurse-manager/home': {
      id: '/nurse-manager/home'
      path: '/home'
      fullPath: '/nurse-manager/home'
      preLoaderRoute: typeof NurseManagerHomeRouteImport
      parentRoute: typeof NurseManagerRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface NurseManagerRouteChildren {
  NurseManagerHomeRoute: typeof NurseManagerHomeRoute
  NurseManagerRequestApplicationRoute: typeof NurseManagerRequestApplicationRoute
  NurseManagerRequestOverviewRoute: typeof NurseManagerRequestOverviewRoute
  NurseManagerRosterPlanningRoute: typeof NurseManagerRosterPlanningRoute
  NurseManagerSettingsRoute: typeof NurseManagerSettingsRoute
  NurseManagerWardStaffDirectoryRoute: typeof NurseManagerWardStaffDirectoryRoute
  NurseManagerIndexRoute: typeof NurseManagerIndexRoute
}

const NurseManagerRouteChildren: NurseManagerRouteChildren = {
  NurseManagerHomeRoute: NurseManagerHomeRoute,
  NurseManagerRequestApplicationRoute: NurseManagerRequestApplicationRoute,
  NurseManagerRequestOverviewRoute: NurseManagerRequestOverviewRoute,
  NurseManagerRosterPlanningRoute: NurseManagerRosterPlanningRoute,
  NurseManagerSettingsRoute: NurseManagerSettingsRoute,
  NurseManagerWardStaffDirectoryRoute: NurseManagerWardStaffDirectoryRoute,
  NurseManagerIndexRoute: NurseManagerIndexRoute,
}

const NurseManagerRouteWithChildren = NurseManagerRoute._addFileChildren(
  NurseManagerRouteChildren,
)

interface WardStaffRouteChildren {
  WardStaffHomeRoute: typeof WardStaffHomeRoute
  WardStaffLeaveRequestRoute: typeof WardStaffLeaveRequestRoute
  WardStaffLeaveandshiftrequestRoute: typeof WardStaffLeaveandshiftrequestRoute
  WardStaffRequestApplicationRoute: typeof WardStaffRequestApplicationRoute
  WardStaffSettingsRoute: typeof WardStaffSettingsRoute
  WardStaffShiftRequestRoute: typeof WardStaffShiftRequestRoute
  WardStaffStaffrosterscheduleRoute: typeof WardStaffStaffrosterscheduleRoute
  WardStaffIndexRoute: typeof WardStaffIndexRoute
}

const WardStaffRouteChildren: WardStaffRouteChildren = {
  WardStaffHomeRoute: WardStaffHomeRoute,
  WardStaffLeaveRequestRoute: WardStaffLeaveRequestRoute,
  WardStaffLeaveandshiftrequestRoute: WardStaffLeaveandshiftrequestRoute,
  WardStaffRequestApplicationRoute: WardStaffRequestApplicationRoute,
  WardStaffSettingsRoute: WardStaffSettingsRoute,
  WardStaffShiftRequestRoute: WardStaffShiftRequestRoute,
  WardStaffStaffrosterscheduleRoute: WardStaffStaffrosterscheduleRoute,
  WardStaffIndexRoute: WardStaffIndexRoute,
}

const WardStaffRouteWithChildren = WardStaffRoute._addFileChildren(
  WardStaffRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  NurseManagerRoute: NurseManagerRouteWithChildren,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  WardStaffRoute: WardStaffRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
