/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WardStaffRouteImport } from './routes/_wardStaff'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as NurseManagerIndexRouteImport } from './routes/nurseManager/index'
import { Route as WardStaffIndexRouteImport } from './routes/_wardStaff/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as WardStaffStaffrosterscheduleRouteImport } from './routes/_wardStaff/staffrosterschedule'
import { Route as WardStaffShiftRequestRouteImport } from './routes/_wardStaff/shift-request'
import { Route as WardStaffSettingsRouteImport } from './routes/_wardStaff/settings'
import { Route as WardStaffRequestApplicationRouteImport } from './routes/_wardStaff/request-application'
import { Route as WardStaffLeaveandshiftrequestRouteImport } from './routes/_wardStaff/leaveandshiftrequest'
import { Route as WardStaffLeaveRequestRouteImport } from './routes/_wardStaff/leave-request'
import { Route as WardStaffHomeRouteImport } from './routes/_wardStaff/home'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WardStaffRoute = WardStaffRouteImport.update({
  id: '/_wardStaff',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseManagerIndexRoute = NurseManagerIndexRouteImport.update({
  id: '/nurseManager/',
  path: '/nurseManager/',
  getParentRoute: () => rootRouteImport,
} as any)
const WardStaffIndexRoute = WardStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WardStaffRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const WardStaffStaffrosterscheduleRoute =
  WardStaffStaffrosterscheduleRouteImport.update({
    id: '/staffrosterschedule',
    path: '/staffrosterschedule',
    getParentRoute: () => WardStaffRoute,
  } as any)
const WardStaffShiftRequestRoute = WardStaffShiftRequestRouteImport.update({
  id: '/shift-request',
  path: '/shift-request',
  getParentRoute: () => WardStaffRoute,
} as any)
const WardStaffSettingsRoute = WardStaffSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WardStaffRoute,
} as any)
const WardStaffRequestApplicationRoute =
  WardStaffRequestApplicationRouteImport.update({
    id: '/request-application',
    path: '/request-application',
    getParentRoute: () => WardStaffRoute,
  } as any)
const WardStaffLeaveandshiftrequestRoute =
  WardStaffLeaveandshiftrequestRouteImport.update({
    id: '/leaveandshiftrequest',
    path: '/leaveandshiftrequest',
    getParentRoute: () => WardStaffRoute,
  } as any)
const WardStaffLeaveRequestRoute = WardStaffLeaveRequestRouteImport.update({
  id: '/leave-request',
  path: '/leave-request',
  getParentRoute: () => WardStaffRoute,
} as any)
const WardStaffHomeRoute = WardStaffHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => WardStaffRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WardStaffIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/home': typeof WardStaffHomeRoute
  '/leave-request': typeof WardStaffLeaveRequestRoute
  '/leaveandshiftrequest': typeof WardStaffLeaveandshiftrequestRoute
  '/request-application': typeof WardStaffRequestApplicationRoute
  '/settings': typeof WardStaffSettingsRoute
  '/shift-request': typeof WardStaffShiftRequestRoute
  '/staffrosterschedule': typeof WardStaffStaffrosterscheduleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/nurseManager/': typeof NurseManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof WardStaffIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/home': typeof WardStaffHomeRoute
  '/leave-request': typeof WardStaffLeaveRequestRoute
  '/leaveandshiftrequest': typeof WardStaffLeaveandshiftrequestRoute
  '/request-application': typeof WardStaffRequestApplicationRoute
  '/settings': typeof WardStaffSettingsRoute
  '/shift-request': typeof WardStaffShiftRequestRoute
  '/staffrosterschedule': typeof WardStaffStaffrosterscheduleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/nurseManager': typeof NurseManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_wardStaff': typeof WardStaffRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_wardStaff/home': typeof WardStaffHomeRoute
  '/_wardStaff/leave-request': typeof WardStaffLeaveRequestRoute
  '/_wardStaff/leaveandshiftrequest': typeof WardStaffLeaveandshiftrequestRoute
  '/_wardStaff/request-application': typeof WardStaffRequestApplicationRoute
  '/_wardStaff/settings': typeof WardStaffSettingsRoute
  '/_wardStaff/shift-request': typeof WardStaffShiftRequestRoute
  '/_wardStaff/staffrosterschedule': typeof WardStaffStaffrosterscheduleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_wardStaff/': typeof WardStaffIndexRoute
  '/nurseManager/': typeof NurseManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/home'
    | '/leave-request'
    | '/leaveandshiftrequest'
    | '/request-application'
    | '/settings'
    | '/shift-request'
    | '/staffrosterschedule'
    | '/auth/callback'
    | '/nurseManager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/home'
    | '/leave-request'
    | '/leaveandshiftrequest'
    | '/request-application'
    | '/settings'
    | '/shift-request'
    | '/staffrosterschedule'
    | '/auth/callback'
    | '/nurseManager'
  id:
    | '__root__'
    | '/_layout'
    | '/_wardStaff'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_wardStaff/home'
    | '/_wardStaff/leave-request'
    | '/_wardStaff/leaveandshiftrequest'
    | '/_wardStaff/request-application'
    | '/_wardStaff/settings'
    | '/_wardStaff/shift-request'
    | '/_wardStaff/staffrosterschedule'
    | '/auth/callback'
    | '/_wardStaff/'
    | '/nurseManager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  WardStaffRoute: typeof WardStaffRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  NurseManagerIndexRoute: typeof NurseManagerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_wardStaff': {
      id: '/_wardStaff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WardStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurseManager/': {
      id: '/nurseManager/'
      path: '/nurseManager'
      fullPath: '/nurseManager/'
      preLoaderRoute: typeof NurseManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_wardStaff/': {
      id: '/_wardStaff/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WardStaffIndexRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_wardStaff/staffrosterschedule': {
      id: '/_wardStaff/staffrosterschedule'
      path: '/staffrosterschedule'
      fullPath: '/staffrosterschedule'
      preLoaderRoute: typeof WardStaffStaffrosterscheduleRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/_wardStaff/shift-request': {
      id: '/_wardStaff/shift-request'
      path: '/shift-request'
      fullPath: '/shift-request'
      preLoaderRoute: typeof WardStaffShiftRequestRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/_wardStaff/settings': {
      id: '/_wardStaff/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WardStaffSettingsRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/_wardStaff/request-application': {
      id: '/_wardStaff/request-application'
      path: '/request-application'
      fullPath: '/request-application'
      preLoaderRoute: typeof WardStaffRequestApplicationRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/_wardStaff/leaveandshiftrequest': {
      id: '/_wardStaff/leaveandshiftrequest'
      path: '/leaveandshiftrequest'
      fullPath: '/leaveandshiftrequest'
      preLoaderRoute: typeof WardStaffLeaveandshiftrequestRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/_wardStaff/leave-request': {
      id: '/_wardStaff/leave-request'
      path: '/leave-request'
      fullPath: '/leave-request'
      preLoaderRoute: typeof WardStaffLeaveRequestRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/_wardStaff/home': {
      id: '/_wardStaff/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof WardStaffHomeRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface WardStaffRouteChildren {
  WardStaffHomeRoute: typeof WardStaffHomeRoute
  WardStaffLeaveRequestRoute: typeof WardStaffLeaveRequestRoute
  WardStaffLeaveandshiftrequestRoute: typeof WardStaffLeaveandshiftrequestRoute
  WardStaffRequestApplicationRoute: typeof WardStaffRequestApplicationRoute
  WardStaffSettingsRoute: typeof WardStaffSettingsRoute
  WardStaffShiftRequestRoute: typeof WardStaffShiftRequestRoute
  WardStaffStaffrosterscheduleRoute: typeof WardStaffStaffrosterscheduleRoute
  WardStaffIndexRoute: typeof WardStaffIndexRoute
}

const WardStaffRouteChildren: WardStaffRouteChildren = {
  WardStaffHomeRoute: WardStaffHomeRoute,
  WardStaffLeaveRequestRoute: WardStaffLeaveRequestRoute,
  WardStaffLeaveandshiftrequestRoute: WardStaffLeaveandshiftrequestRoute,
  WardStaffRequestApplicationRoute: WardStaffRequestApplicationRoute,
  WardStaffSettingsRoute: WardStaffSettingsRoute,
  WardStaffShiftRequestRoute: WardStaffShiftRequestRoute,
  WardStaffStaffrosterscheduleRoute: WardStaffStaffrosterscheduleRoute,
  WardStaffIndexRoute: WardStaffIndexRoute,
}

const WardStaffRouteWithChildren = WardStaffRoute._addFileChildren(
  WardStaffRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  WardStaffRoute: WardStaffRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  NurseManagerIndexRoute: NurseManagerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
