/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as NurseManagerRouteImport } from './routes/nurse-manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WardStaffRouteImport } from './routes/_wardStaff'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as NurseManagerIndexRouteImport } from './routes/nurse-manager/index'
import { Route as WardStaffIndexRouteImport } from './routes/_wardStaff/index'
import { Route as NurseManagerWardStaffDirectoryRouteImport } from './routes/nurse-manager/ward-staff-directory'
import { Route as NurseManagerShiftOverviewRouteImport } from './routes/nurse-manager/shift-overview'
import { Route as NurseManagerSettingsRouteImport } from './routes/nurse-manager/settings'
import { Route as NurseManagerRosterPlanningRouteImport } from './routes/nurse-manager/roster-planning'
import { Route as NurseManagerLeaveOverviewRouteImport } from './routes/nurse-manager/leave-overview'
import { Route as NurseManagerHomeRouteImport } from './routes/nurse-manager/home'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as WardStaffStaffrosterscheduleRouteImport } from './routes/_wardStaff/staffrosterschedule'
import { Route as WardStaffShiftRequestRouteImport } from './routes/_wardStaff/shift-request'
import { Route as WardStaffSettingsRouteImport } from './routes/_wardStaff/settings'
import { Route as WardStaffLeaveandshiftrequestRouteImport } from './routes/_wardStaff/leaveandshiftrequest'
import { Route as WardStaffLeaveRequestRouteImport } from './routes/_wardStaff/leave-request'
import { Route as WardStaffHomeRouteImport } from './routes/_wardStaff/home'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseManagerRoute = NurseManagerRouteImport.update({
  id: '/nurse-manager',
  path: '/nurse-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WardStaffRoute = WardStaffRouteImport.update({
  id: '/_wardStaff',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseManagerIndexRoute = NurseManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NurseManagerRoute,
} as any)
const WardStaffIndexRoute = WardStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WardStaffRoute,
} as any)
const NurseManagerWardStaffDirectoryRoute =
  NurseManagerWardStaffDirectoryRouteImport.update({
    id: '/ward-staff-directory',
    path: '/ward-staff-directory',
    getParentRoute: () => NurseManagerRoute,
  } as any)
const NurseManagerShiftOverviewRoute =
  NurseManagerShiftOverviewRouteImport.update({
    id: '/shift-overview',
    path: '/shift-overview',
    getParentRoute: () => NurseManagerRoute,
  } as any)
const NurseManagerSettingsRoute = NurseManagerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => NurseManagerRoute,
} as any)
const NurseManagerRosterPlanningRoute =
  NurseManagerRosterPlanningRouteImport.update({
    id: '/roster-planning',
    path: '/roster-planning',
    getParentRoute: () => NurseManagerRoute,
  } as any)
const NurseManagerLeaveOverviewRoute =
  NurseManagerLeaveOverviewRouteImport.update({
    id: '/leave-overview',
    path: '/leave-overview',
    getParentRoute: () => NurseManagerRoute,
  } as any)
const NurseManagerHomeRoute = NurseManagerHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => NurseManagerRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const WardStaffStaffrosterscheduleRoute =
  WardStaffStaffrosterscheduleRouteImport.update({
    id: '/staffrosterschedule',
    path: '/staffrosterschedule',
    getParentRoute: () => WardStaffRoute,
  } as any)
const WardStaffShiftRequestRoute = WardStaffShiftRequestRouteImport.update({
  id: '/shift-request',
  path: '/shift-request',
  getParentRoute: () => WardStaffRoute,
} as any)
const WardStaffSettingsRoute = WardStaffSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WardStaffRoute,
} as any)
const WardStaffLeaveandshiftrequestRoute =
  WardStaffLeaveandshiftrequestRouteImport.update({
    id: '/leaveandshiftrequest',
    path: '/leaveandshiftrequest',
    getParentRoute: () => WardStaffRoute,
  } as any)
const WardStaffLeaveRequestRoute = WardStaffLeaveRequestRouteImport.update({
  id: '/leave-request',
  path: '/leave-request',
  getParentRoute: () => WardStaffRoute,
} as any)
const WardStaffHomeRoute = WardStaffHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => WardStaffRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/nurse-manager': typeof NurseManagerRouteWithChildren
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/home': typeof WardStaffHomeRoute
  '/leave-request': typeof WardStaffLeaveRequestRoute
  '/leaveandshiftrequest': typeof WardStaffLeaveandshiftrequestRoute
  '/settings': typeof WardStaffSettingsRoute
  '/shift-request': typeof WardStaffShiftRequestRoute
  '/staffrosterschedule': typeof WardStaffStaffrosterscheduleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/nurse-manager/home': typeof NurseManagerHomeRoute
  '/nurse-manager/leave-overview': typeof NurseManagerLeaveOverviewRoute
  '/nurse-manager/roster-planning': typeof NurseManagerRosterPlanningRoute
  '/nurse-manager/settings': typeof NurseManagerSettingsRoute
  '/nurse-manager/shift-overview': typeof NurseManagerShiftOverviewRoute
  '/nurse-manager/ward-staff-directory': typeof NurseManagerWardStaffDirectoryRoute
  '/': typeof WardStaffIndexRoute
  '/nurse-manager/': typeof NurseManagerIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/home': typeof WardStaffHomeRoute
  '/leave-request': typeof WardStaffLeaveRequestRoute
  '/leaveandshiftrequest': typeof WardStaffLeaveandshiftrequestRoute
  '/settings': typeof WardStaffSettingsRoute
  '/shift-request': typeof WardStaffShiftRequestRoute
  '/staffrosterschedule': typeof WardStaffStaffrosterscheduleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/nurse-manager/home': typeof NurseManagerHomeRoute
  '/nurse-manager/leave-overview': typeof NurseManagerLeaveOverviewRoute
  '/nurse-manager/roster-planning': typeof NurseManagerRosterPlanningRoute
  '/nurse-manager/settings': typeof NurseManagerSettingsRoute
  '/nurse-manager/shift-overview': typeof NurseManagerShiftOverviewRoute
  '/nurse-manager/ward-staff-directory': typeof NurseManagerWardStaffDirectoryRoute
  '/': typeof WardStaffIndexRoute
  '/nurse-manager': typeof NurseManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_wardStaff': typeof WardStaffRouteWithChildren
  '/login': typeof LoginRoute
  '/nurse-manager': typeof NurseManagerRouteWithChildren
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_wardStaff/home': typeof WardStaffHomeRoute
  '/_wardStaff/leave-request': typeof WardStaffLeaveRequestRoute
  '/_wardStaff/leaveandshiftrequest': typeof WardStaffLeaveandshiftrequestRoute
  '/_wardStaff/settings': typeof WardStaffSettingsRoute
  '/_wardStaff/shift-request': typeof WardStaffShiftRequestRoute
  '/_wardStaff/staffrosterschedule': typeof WardStaffStaffrosterscheduleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/nurse-manager/home': typeof NurseManagerHomeRoute
  '/nurse-manager/leave-overview': typeof NurseManagerLeaveOverviewRoute
  '/nurse-manager/roster-planning': typeof NurseManagerRosterPlanningRoute
  '/nurse-manager/settings': typeof NurseManagerSettingsRoute
  '/nurse-manager/shift-overview': typeof NurseManagerShiftOverviewRoute
  '/nurse-manager/ward-staff-directory': typeof NurseManagerWardStaffDirectoryRoute
  '/_wardStaff/': typeof WardStaffIndexRoute
  '/nurse-manager/': typeof NurseManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/nurse-manager'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/home'
    | '/leave-request'
    | '/leaveandshiftrequest'
    | '/settings'
    | '/shift-request'
    | '/staffrosterschedule'
    | '/auth/callback'
    | '/nurse-manager/home'
    | '/nurse-manager/leave-overview'
    | '/nurse-manager/roster-planning'
    | '/nurse-manager/settings'
    | '/nurse-manager/shift-overview'
    | '/nurse-manager/ward-staff-directory'
    | '/'
    | '/nurse-manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/home'
    | '/leave-request'
    | '/leaveandshiftrequest'
    | '/settings'
    | '/shift-request'
    | '/staffrosterschedule'
    | '/auth/callback'
    | '/nurse-manager/home'
    | '/nurse-manager/leave-overview'
    | '/nurse-manager/roster-planning'
    | '/nurse-manager/settings'
    | '/nurse-manager/shift-overview'
    | '/nurse-manager/ward-staff-directory'
    | '/'
    | '/nurse-manager'
  id:
    | '__root__'
    | '/_layout'
    | '/_wardStaff'
    | '/login'
    | '/nurse-manager'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_wardStaff/home'
    | '/_wardStaff/leave-request'
    | '/_wardStaff/leaveandshiftrequest'
    | '/_wardStaff/settings'
    | '/_wardStaff/shift-request'
    | '/_wardStaff/staffrosterschedule'
    | '/auth/callback'
    | '/nurse-manager/home'
    | '/nurse-manager/leave-overview'
    | '/nurse-manager/roster-planning'
    | '/nurse-manager/settings'
    | '/nurse-manager/shift-overview'
    | '/nurse-manager/ward-staff-directory'
    | '/_wardStaff/'
    | '/nurse-manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  WardStaffRoute: typeof WardStaffRouteWithChildren
  LoginRoute: typeof LoginRoute
  NurseManagerRoute: typeof NurseManagerRouteWithChildren
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse-manager': {
      id: '/nurse-manager'
      path: '/nurse-manager'
      fullPath: '/nurse-manager'
      preLoaderRoute: typeof NurseManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_wardStaff': {
      id: '/_wardStaff'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WardStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse-manager/': {
      id: '/nurse-manager/'
      path: '/'
      fullPath: '/nurse-manager/'
      preLoaderRoute: typeof NurseManagerIndexRouteImport
      parentRoute: typeof NurseManagerRoute
    }
    '/_wardStaff/': {
      id: '/_wardStaff/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WardStaffIndexRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/nurse-manager/ward-staff-directory': {
      id: '/nurse-manager/ward-staff-directory'
      path: '/ward-staff-directory'
      fullPath: '/nurse-manager/ward-staff-directory'
      preLoaderRoute: typeof NurseManagerWardStaffDirectoryRouteImport
      parentRoute: typeof NurseManagerRoute
    }
    '/nurse-manager/shift-overview': {
      id: '/nurse-manager/shift-overview'
      path: '/shift-overview'
      fullPath: '/nurse-manager/shift-overview'
      preLoaderRoute: typeof NurseManagerShiftOverviewRouteImport
      parentRoute: typeof NurseManagerRoute
    }
    '/nurse-manager/settings': {
      id: '/nurse-manager/settings'
      path: '/settings'
      fullPath: '/nurse-manager/settings'
      preLoaderRoute: typeof NurseManagerSettingsRouteImport
      parentRoute: typeof NurseManagerRoute
    }
    '/nurse-manager/roster-planning': {
      id: '/nurse-manager/roster-planning'
      path: '/roster-planning'
      fullPath: '/nurse-manager/roster-planning'
      preLoaderRoute: typeof NurseManagerRosterPlanningRouteImport
      parentRoute: typeof NurseManagerRoute
    }
    '/nurse-manager/leave-overview': {
      id: '/nurse-manager/leave-overview'
      path: '/leave-overview'
      fullPath: '/nurse-manager/leave-overview'
      preLoaderRoute: typeof NurseManagerLeaveOverviewRouteImport
      parentRoute: typeof NurseManagerRoute
    }
    '/nurse-manager/home': {
      id: '/nurse-manager/home'
      path: '/home'
      fullPath: '/nurse-manager/home'
      preLoaderRoute: typeof NurseManagerHomeRouteImport
      parentRoute: typeof NurseManagerRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_wardStaff/staffrosterschedule': {
      id: '/_wardStaff/staffrosterschedule'
      path: '/staffrosterschedule'
      fullPath: '/staffrosterschedule'
      preLoaderRoute: typeof WardStaffStaffrosterscheduleRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/_wardStaff/shift-request': {
      id: '/_wardStaff/shift-request'
      path: '/shift-request'
      fullPath: '/shift-request'
      preLoaderRoute: typeof WardStaffShiftRequestRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/_wardStaff/settings': {
      id: '/_wardStaff/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WardStaffSettingsRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/_wardStaff/leaveandshiftrequest': {
      id: '/_wardStaff/leaveandshiftrequest'
      path: '/leaveandshiftrequest'
      fullPath: '/leaveandshiftrequest'
      preLoaderRoute: typeof WardStaffLeaveandshiftrequestRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/_wardStaff/leave-request': {
      id: '/_wardStaff/leave-request'
      path: '/leave-request'
      fullPath: '/leave-request'
      preLoaderRoute: typeof WardStaffLeaveRequestRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/_wardStaff/home': {
      id: '/_wardStaff/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof WardStaffHomeRouteImport
      parentRoute: typeof WardStaffRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface WardStaffRouteChildren {
  WardStaffHomeRoute: typeof WardStaffHomeRoute
  WardStaffLeaveRequestRoute: typeof WardStaffLeaveRequestRoute
  WardStaffLeaveandshiftrequestRoute: typeof WardStaffLeaveandshiftrequestRoute
  WardStaffSettingsRoute: typeof WardStaffSettingsRoute
  WardStaffShiftRequestRoute: typeof WardStaffShiftRequestRoute
  WardStaffStaffrosterscheduleRoute: typeof WardStaffStaffrosterscheduleRoute
  WardStaffIndexRoute: typeof WardStaffIndexRoute
}

const WardStaffRouteChildren: WardStaffRouteChildren = {
  WardStaffHomeRoute: WardStaffHomeRoute,
  WardStaffLeaveRequestRoute: WardStaffLeaveRequestRoute,
  WardStaffLeaveandshiftrequestRoute: WardStaffLeaveandshiftrequestRoute,
  WardStaffSettingsRoute: WardStaffSettingsRoute,
  WardStaffShiftRequestRoute: WardStaffShiftRequestRoute,
  WardStaffStaffrosterscheduleRoute: WardStaffStaffrosterscheduleRoute,
  WardStaffIndexRoute: WardStaffIndexRoute,
}

const WardStaffRouteWithChildren = WardStaffRoute._addFileChildren(
  WardStaffRouteChildren,
)

interface NurseManagerRouteChildren {
  NurseManagerHomeRoute: typeof NurseManagerHomeRoute
  NurseManagerLeaveOverviewRoute: typeof NurseManagerLeaveOverviewRoute
  NurseManagerRosterPlanningRoute: typeof NurseManagerRosterPlanningRoute
  NurseManagerSettingsRoute: typeof NurseManagerSettingsRoute
  NurseManagerShiftOverviewRoute: typeof NurseManagerShiftOverviewRoute
  NurseManagerWardStaffDirectoryRoute: typeof NurseManagerWardStaffDirectoryRoute
  NurseManagerIndexRoute: typeof NurseManagerIndexRoute
}

const NurseManagerRouteChildren: NurseManagerRouteChildren = {
  NurseManagerHomeRoute: NurseManagerHomeRoute,
  NurseManagerLeaveOverviewRoute: NurseManagerLeaveOverviewRoute,
  NurseManagerRosterPlanningRoute: NurseManagerRosterPlanningRoute,
  NurseManagerSettingsRoute: NurseManagerSettingsRoute,
  NurseManagerShiftOverviewRoute: NurseManagerShiftOverviewRoute,
  NurseManagerWardStaffDirectoryRoute: NurseManagerWardStaffDirectoryRoute,
  NurseManagerIndexRoute: NurseManagerIndexRoute,
}

const NurseManagerRouteWithChildren = NurseManagerRoute._addFileChildren(
  NurseManagerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  WardStaffRoute: WardStaffRouteWithChildren,
  LoginRoute: LoginRoute,
  NurseManagerRoute: NurseManagerRouteWithChildren,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
